use std::collections::HashSet;

use crate::plan::{DiagnosticSeverity, PlanDiagnostic, Step};

/// Generation-time best-effort validation of tool references.
/// Validates against tool descriptions available when the plan was generated by the LLM.
/// Provides fast feedback during the LLM retry loop so invalid plans can be rejected and regenerated.
/// Plans may be serialized and executed later with a different tool registry, so this check alone is not authoritative.
/// Runtime execution still performs authoritative tool lookup when dispatching each tool call.
pub(crate) fn validate_tool_reference(
    step: &Step,
    diagnostics: &mut Vec<PlanDiagnostic>,
    available_tool_ids: &HashSet<&str>,
) {
    if let Step::ToolStep { tool_id, .. } = step
        && !available_tool_ids.contains(tool_id.as_str())
    {
        diagnostics.push(PlanDiagnostic {
            severity: DiagnosticSeverity::Error,
            message: format!("Unknown tool_id '{tool_id}'"),
            variable_name: None,
        });
    }
}
